name: Build and run on all OSes
on: [push]
jobs:
  release:
    runs-on: mac-os-latest
#     windows-latest, mac-os-latest
#     runs-on: ${{ matrix.os }}

#     strategy:
#         matrix:
#             os: [windows-latest, mac-os-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      # - name: Go run
      #   run: |
      #     sudo go run . -remote "heisse.de"
      - name: Build
        run: go build -v ./...
      - name: Run the binary
        run: |
          sudo ./my_traceroute -remote "heisse.de"